apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: default
  labels:
    app: httpbin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
      annotations:
        # Ensure Istio sidecar is injected
        sidecar.istio.io/inject: "true"
        # Override Envoy stats matcher to include upstream request metrics
        proxy.istio.io/config: |-
          proxyStatsMatcher:
            inclusionRegexps:
            - ".*_upstream_rq_.*"
            - ".*inbound.*"
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: default
  labels:
    app: httpbin
spec:
  selector:
    app: httpbin
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin
  namespace: default
spec:
  host: httpbin.default.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN  # Ensures even distribution across backend pods
    connectionPool:
      http:
        http2MaxRequests: 10
    outlierDetection:
      consecutiveGatewayErrors: 3
      consecutive5xxErrors: 0
      interval: 5s
      baseEjectionTime: 1m
      maxEjectionPercent: 100
